src/Entity/IssueComment.php
<?php

namespace App\Entity;

use App\Repository\IssueCommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IssueCommentRepository::class)
 */
class IssueComment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Issue::class, inversedBy="issueComments")
     */
    private $issue;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIssue(): ?Issue
    {
        return $this->issue;
    }

    public function setIssue(?Issue $issue): self
    {
        $this->issue = $issue;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/IssueCommentType.php
<?php

namespace App\Form;

use App\Entity\IssueComment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IssueCommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => IssueComment::class,
        ]);
    }
}

src/Controller/IssueCommentController.php
<?php

namespace App\Controller;

use App\Entity\Issue;
use App\Entity\IssueComment;
use App\Form\IssueCommentType;
use App\Repository\IssueCommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/issue/comment")
 */
class IssueCommentController extends AbstractController
{
    /**
     * @Route("/", name="issue_comment_index", methods={"GET"})
     */
    public function index(IssueCommentRepository $issueCommentRepository): Response
    {
        return $this->render('issue_comment/index.html.twig', [
            'issue_comments' => $issueCommentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="issue_comment_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $issueComment = new IssueComment();
        $issueComment->setContent($request->request->get('content'));
        $issueComment->setUpdatedAt(new \DateTimeImmutable());
        $issueComment->setIssue($this->getDoctrine()->getRepository(Issue::class)->find($request->request->get('issue')));
        $entityManager->persist($issueComment);
        $entityManager->flush();

        return $this->json('ok');
    }

    /**
     * @Route("/{id}", name="issue_comment_show", methods={"GET"})
     */
    public function show(IssueComment $issueComment): Response
    {
        return $this->render('issue_comment/show.html.twig', [
            'issue_comment' => $issueComment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="issue_comment_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, IssueComment $issueComment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(IssueCommentType::class, $issueComment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('issue_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('issue_comment/edit.html.twig', [
            'issue_comment' => $issueComment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="issue_comment_delete", methods={"POST"})
     */
    public function delete(Request $request, IssueComment $issueComment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$issueComment->getId(), $request->request->get('_token'))) {
            $entityManager->remove($issueComment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('issue_comment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/issue_comment/_delete_form.html.twig
<form method="post" action="{{ path('issue_comment_delete', {'id': issue_comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ issue_comment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/issue_comment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/issue_comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit IssueComment{% endblock %}

{% block body %}
    <h1>Edit IssueComment</h1>

    {{ include('issue_comment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('issue_comment_index') }}">back to list</a>

    {{ include('issue_comment/_delete_form.html.twig') }}
{% endblock %}

templates/issue_comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}IssueComment index{% endblock %}

{% block body %}
    <h1>IssueComment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for issue_comment in issue_comments %}
            <tr>
                <td>{{ issue_comment.id }}</td>
                <td>{{ issue_comment.content }}</td>
                <td>{{ issue_comment.updatedAt ? issue_comment.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('issue_comment_show', {'id': issue_comment.id}) }}">show</a>
                    <a href="{{ path('issue_comment_edit', {'id': issue_comment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('issue_comment_new') }}">Create new</a>
{% endblock %}

templates/issue_comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New IssueComment{% endblock %}

{% block body %}
    <h1>Create new IssueComment</h1>

    {{ include('issue_comment/_form.html.twig') }}

    <a href="{{ path('issue_comment_index') }}">back to list</a>
{% endblock %}

templates/issue_comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}IssueComment{% endblock %}

{% block body %}
    <h1>IssueComment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ issue_comment.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ issue_comment.content }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ issue_comment.updatedAt ? issue_comment.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('issue_comment_index') }}">back to list</a>

    <a href="{{ path('issue_comment_edit', {'id': issue_comment.id}) }}">edit</a>

    {{ include('issue_comment/_delete_form.html.twig') }}
{% endblock %}